public class ApplicationService {

    public static void validateApplications(
        List<Application__c> applications
    ) {

        Set<Id> studentIds = new Set<Id>();
        Set<Id> jobIds = new Set<Id>();

        for(Application__c app : applications){

            if(app.Student__c != null){
                studentIds.add(app.Student__c);
            }

            if(app.Job__c != null){
                jobIds.add(app.Job__c);
            }
        }

        Map<Id, Student__c> students =
            new Map<Id, Student__c>([
                SELECT Id,
                       CGPA__c,
                       Active_Backlogs__c,
                       Branch__c
                FROM Student__c
                WHERE Id IN :studentIds
            ]);

        Map<Id, Job__c> jobs =
            new Map<Id, Job__c>([
                SELECT Id,
                       Minimum_CGPA__c,
                       Allowed_Backlogs__c
                FROM Job__c
                WHERE Id IN :jobIds
            ]);

        for(Application__c app : applications){

            Student__c student =
                students.get(app.Student__c);

            Job__c job =
                jobs.get(app.Job__c);

            if(student != null && job != null){

                if(student.CGPA__c >= job.Minimum_CGPA__c){

                    app.Status__c = 'Eligible';

                }else{

                    app.Status__c = 'Rejected';

                }

            }

        }

    }

    public static void processSelections(
        List<Application__c> applications,
        Map<Id, Application__c> oldMap
    ){

        List<Student__c> studentsToUpdate =
            new List<Student__c>();

        // TODO:
        // Compare Trigger.oldMap and Trigger.new
        // Update Student Placement Status
        // Perform one DML operation

        if(!studentsToUpdate.isEmpty()){

            update studentsToUpdate;

        }

    }

}